title: Dennis Kontic
description: Cybersecurity Graduate | Security Operations | Blue Team | DFIR | AI Security | Cybersecurity Education
show_downloads: false
theme: jekyll-theme-cayman
google_analytics:
